version: "3"
services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env

  telegram_bot:
    build:
      context: ./telegram_bot
    env_file:
      - ./telegram_bot/.env
    depends_on:
      - api
